### ISSUE TITLE
fava_investor not loading 

### ISSUE THREAD

**Issue by pfrancois** [redstreet/fava_investor#47] opened 2020-05-29 14:08 UTC
when i try to use it even with your beancount example, i have `"loading http://localhost:5000/huge-example-file/extension/investor failed" `
and in the console of fava i have 
```
  File "c:\program files\python38\lib\site-packages\jinja2\lexer.py", line 381, in expect
    raise TemplateSyntaxError("expected token %r, got %r" %
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '_'
```
so basically noting work :(

**Comment by redstreet** [comment] 2020-07-21 18:19
Hmm, this may be Windows specific, or specific to a version of jinja2 that you are using. Is there a different platform you could try this on?

**Comment by redstreet** [comment] 2021-05-29 05:53
Closing this as a duplicate of #51.

**Closed by redstreet** 2021-05-29 05:53 UTC
