### ISSUE TITLE
[Feature] Use implicit prices

### ISSUE THREAD

**Issue by putzwasser** [redstreet/fava_investor#77] opened 2022-11-13 10:02 UTC
Fava currently doesn't use the price information provided in postings:

```
plugin "beancount.plugins.implicit_prices"
2000-01-01 * "" "Buy new Asset"
  Assets:Investments:MyNewAsset                                  1 NEWASSET {1000 USD} @ 1000 USD
  Assets:Cash
```

Will lead to fava exiting, as there is no explicit price directive.

You need to explicitly add a price directive for `NEWASSET`:
```
plugin "beancount.plugins.implicit_prices"
2000-01-01 * "" "Buy new Asset"
  Assets:Investments:MyNewAsset                                  1 NEWASSET {1000 USD} @ 1000 USD
  Assets:Cash

2000-01-01 price NEWASSET 1000 USD
```

I update some assets more or less only via the „implicit“ price directive syntax that beancount provides. It would be nice, if fava_investor would make use of the data.

**Comment by redstreet** [comment] 2022-11-20 22:38
Closing this as: unable to reproduce. Feel free to reopen with a test case.

**Closed by redstreet** 2022-11-20 22:38 UTC
